name: flutter_webrtc_demo
description: A new Flutter application.
version: 1.2.0

environment:
  sdk: "3.0.3"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.0.15
  http: ^1.0.0
  shared_preferences: ^2.1.2
  flutter_webrtc: ^0.9.34

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true

import_sorter:
  comments: false
  # ignored_files:
  #   - \/lib\/*
